### ISSUE TITLE
LOG_LEVEL more verbose than notice with LOG_DEBUG="-..." does not work

### ISSUE THREAD

**Issue by nathannau** [medikoo/log4#19]
I don't know if this is intentional, but when LOG_LEVEL is set to "debug" or "info", LOG_DEBUG is ignored.

**Comment by nathannau** [comment]
In fact the problem arises when the logger is instantiated globally in an imported file.

`file.ts
import log from "log";
const myLogger = log.get("myLogger");

export function myTest() { myLogger.info('info') }
`

`.env
LOG_LEVEL="debug"
DEBUG="-myLogger"
`

**Comment by medikoo** [comment]
@nathannau to clarify:

1. `LOG_LEVEL=debug` will enable all logs (including all debug logs), and then via `LOG_DEBUG` we can only decide which namespaces should not be shown (e.g. `LOG_LEVEL=debug LOG_DEBUG=-db` will result in showing all debug logs aside of those coming from `db` namespace)
2. `LOG_LEVEL=info` will enable all logs down to _info_ level, then via `LOG_DEBUG` we can decide for which namespaces also debug level logs should be shown
